//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Notepad2.Common.rc
//
#define IDR_MAINWND                     100
#define IDC_FINDTEXT                    100
#define IDC_LINENUM                     100
#define IDC_COMMANDLINE                 100
#define IDD_ABOUT                       100
#define IDC_VERSION                     100
#define IDC_HOVER                       100
#define IDC_STYLELIST                   100
#define IDX_BM0                         100
#define IDC_FAVORITESDIR                100
#define IDC_SEARCHEXE                   101
#define IDR_POPUPMENU                   101
#define IDC_EMAIL                       101
#define IDC_STYLEEDIT                   101
#define IDC_REPLACETEXT                 101
#define IDB_DISABLEDTOOLS               101
#define IDI_RUN                         101
#define IDC_COLNUM                      101
#define IDX_BM1                         101
#define IDC_GETFAVORITESDIR             101
#define IDC_GOTOFAVDIR                  101
#define IDC_INDENT                      101
#define IDC_FINDCASE                    102
#define IDC_WEBPAGE                     102
#define IDC_PREVSTYLE                   102
#define IDD_RUN                         102
#define IDB_OPEN                        102
#define IDI_FIND                        102
#define IDX_BM2                         102
#define IDC_AUTOSELECT                  102
#define IDC_FAVORITESDESCR              102
#define IDC_FINDWORD                    103
#define IDC_RESIZEGRIP3                 103
#define IDC_NEXTSTYLE                   103
#define IDB_PREV                        103
#define IDI_STYLES                      103
#define IDX_BM3                         103
#define IDC_WEBPAGE2                    103
#define IDC_FINDSTART                   104
#define IDC_STYLEFONT                   104
#define IDB_NEXT                        104
#define IDX_BM4                         104
#define IDC_FINDREGEXP                  105
#define IDC_STYLEFORE                   105
#define IDX_BM5                         105
#define IDD_FAVORITES                   105
#define IDC_STYLEBACK                   106
#define IDX_BM6                         106
#define IDD_ADDTOFAV                    106
#define IDC_FINDUP                      106
#define IDC_STYLEDEFAULT                107
#define IDX_BM7                         107
#define IDC_FINDCLOSE                   107
#define IDD_LINENUM                     108
#define IDX_BM8                         108
#define IDC_REPLACE                     108
#define IDC_REPLACEALL                  109
#define IDC_REPLACEINSEL                110
#define IDD_REPLACE                     110
#define IDD_STYLESELECT                 111
#define IDC_REPLACEINSEL2               111
#define IDC_COLLECT                     111
#define IDD_STYLECONFIG                 112
#define IDD_PAGESETUP                   116
#define IDI_ASP                         304
#define IDI_C                           305
#define IDI_CS                          306
#define IDI_CFG                         307
#define IDI_CPP                         308
#define IDI_H                           309
#define IDI_INI                         310
#define IDI_JS                          311
#define IDI_NSIS                        312
#define IDI_RC                          313
#define IDI_SQL                         314
#define IDI_TXT                         315
#define IDI_VB                          316
#define IDI_CUE                         317
#define IDR_RT_MANIFEST1                319
#define IDD_FORMAT                      320
#define IDD_COMPILE_NSIS                322
#define IDD_CPP_BATCH_FORMAT            323
#define IDD_SAVE_METHOD                 324
#define IDI_MAK                         326
#define IDI_ICON1                       327
#define IDI_PY                          327
#define IDD_FILEASSOC                   328
#define IDB_CHECK                       330
#define IDD_OPENWITH                    331
#define IDD_EXCEPTION                   332
#define IDD_PROP_GENERAL                333
#define IDD_PROP_EDITOR                 334
#define IDB_BITMAP1                     336
#define IDB_RIGHT                       336
#define IDD_CUSTOM_REGXP                338
#define IDI_ICON2                       339
#define IDI_CSS                         339
#define IDR_NOTEPAD2HTML                342
#define IDR_BINARY1                     345
#define IDR_LINEDRAW                    345
#define IDD_IMPORT_EXPORT               346
#define IDC_COMBO2                      1128
#define IDC_PREDEFINE                   1129
#define IDC_DESCRIPTION                 1131
#define IDC_C                           1132
#define IDC_JAVA                        1133
#define IDC_SPACE                       1134
#define IDC_TAB                         1135
#define IDC_SPACE_NUM                   1136
#define IDC_CLASS                       1137
#define IDC_INDENT_CLASS                1137
#define IDC_SWITCH                      1138
#define IDC_INDENT_SWITCH               1138
#define IDC_CASE                        1139
#define IDC_INDENT_CASE                 1139
#define IDC_BRACKET                     1140
#define IDC_INDENT_BRACKET              1140
#define IDC_BLOCK                       1141
#define IDC_INDENT_BLOCK                1141
#define IDC_NAMESPACE                   1142
#define IDC_INDENT_NAMESPACE            1142
#define IDC_LABEL                       1143
#define IDC_INDENT_LABEL                1143
#define IDC_MAX_INDENT                  1144
#define IDC_MAX_II_SPIN                 1145
#define IDC_SPACE_NUM_SPIN              1146
#define IDC_MIN_CI                      1147
#define IDC_MIN_CI_SPIN                 1148
#define IDC_PREPROCESSOR                1149
#define IDC_INDENT_PREPROCESSOR         1149
#define IDC_CONVERT_TAB                 1150
#define IDC_FILL_EMPTY_LINE             1151
#define IDC_BLOCK_STD                   1154
#define IDC_PAD_BLOCK_HEADER            1155
#define IDC_SEPER_ELSEIF                1156
#define IDC_BLOCK_ATTACH                1157
#define IDC_BLOCK_LINUX                 1158
#define IDC_BLOCK_BCH                   1159
#define IDC_PAD_OPERATION               1160
#define IDC_PAD_PARENT                  1162
#define IDC_MIX_STATEMENT               1163
#define IDC_MIX_BLOCK                   1164
#define IDC_CHECK7                      1165
#define IDC_USECUR                      1165
#define IDC_SAVE_AS                     1166
#define IDC_SAVEAS                      1166
#define IDC_INFO                        1167
#define IDC_TEST                        1169
#define IDC_METHOD                      1170
#define IDC_PATH                        1171
#define IDC_BROWSE                      1172
#define IDC_STATIC1                     1174
#define IDC_SIZEBOX                     1175
#define IDC_PROGRESS1                   1177
#define IDC_PROGRESS                    1177
#define IDC_FAVDIR                      1179
#define IDC_CURDIR                      1179
#define IDC_UP                          1180
#define IDC_FCOLOR                      1181
#define IDC_BCOLOR                      1182
#define IDC_FONT_SIZE                   1183
#define IDC_FONT_BOLD                   1184
#define IDC_FONT_ITALIC                 1185
#define IDC_FONT_UNDERLINE              1186
#define IDC_FGCODE                      1187
#define IDC_BGCODE                      1188
#define IDC_SETDEFAULT                  1188
#define IDC_NAME                        1189
#define IDC_TREE1                       1197
#define IDC_TREEVIEW                    1197
#define IDC_SELALL                      1198
#define IDC_SELNONE                     1199
#define IDC_SELALL2                     1199
#define IDC_COMBO1                      1201
#define IDC_FILTER                      1201
#define IDC_SYMBOL                      1201
#define IDC_ADD                         1206
#define IDC_REMOVE                      1207
#define IDC_STATIC_NAME                 1209
#define IDC_STATIC_PATH                 1210
#define IDC_EDIT1                       1212
#define IDC_EDT_FILE                    1212
#define IDC_WEBPAGE3                    1213
#define IDC_VALUE                       1213
#define IDC_WEBPAGE4                    1214
#define IDC_VALUE2                      1214
#define IDC_WEBPAGE5                    1215
#define IDC_WEBPAGE6                    1216
#define IDC_STATIC_REPLACETEXT          1217
#define IDC_REUSEWINDOW                 1218
#define IDC_ALWAYSONTOP                 1219
#define IDC_MINTOTRAY                   1220
#define IDC_TRANSPARENT                 1221
#define IDC_SHOWFULLPATH                1222
#define IDC_SAVEVEFORERUNNINGTOOLS      1223
#define IDC_ESCMINIMIZE                 1224
#define IDC_ESCEXIT                     1225
#define IDC_NOESNFUNC                   1226
#define IDC_EDGE                        1227
#define IDC_BACKGROUND                  1228
#define IDC_TABWIDTH                    1229
#define IDC_LONGLINES                   1230
#define IDC_TABASSPACE                  1231
#define IDC_SLIDER1                     1232
#define IDC_SLIDER_ALPHA                1232
#define IDC_ALPHA                       1233
#define IDC_DO_FIND                     1234
#define IDC_DO_REPLACE                  1235
#define IDC_DO_COLLECT                  1236
#define IDC_YPOS                        1237
#define IDC_MENU_FIND                   1238
#define IDC_MENU_REPLACE                1239
#define IDC_LIST                        1239
#define IDC_MODIFY                      1242
#define IDC_STATIC_VALUE                1243
#define IDC_STATIC_VALUE2               1244
#define IDC_IE_VIEWER                   1245
#define IDC_CHK_SETTING                 1251
#define IDC_CHK_STYLE                   1252
#define IDC_CHK_FORMATTING              1253
#define IDC_CHK_REGXP                   1254
#define IDC_CHK_MRU                     1255
#define IDC_CHK_TOOLBAR                 1256
#define IDC_CHK_WINDOWS_POSITION        1257
#define IDS_APPTITLE                    10000
#define IDS_APPTITLE_PASTEBOARD         10001
#define IDS_UNTITLED                    10002
#define IDS_READONLY                    10003
#define IDS_DOCPOS                      10004
#define IDS_DOCSIZE                     10005
#define IDS_VERSION                     10005
#define IDS_LOADFILE                    10006
#define IDS_SAVEFILE                    10007
#define IDS_PRINTFILE                   10008
#define IDS_LINKDESCRIPTION             10009
#define IDS_ERR_FINDTOOLONG             10010
#define IDS_ERR_COMPILE_NSIS            10011
#define IDS_FORMATTED                   10012
#define IDS_ERR_OPENFILE                10013
#define IDS_CLOSE                       10014
#define IDS_FORMATTING                  10015
#define IDS_FILTER_SUPPORT              10016
#define IDS_BYTES                       10017
#define IDS_COMMENT                     10018
#define IDS_UNCOMMENT                   10019
#define IDS_ERR_EMPTRY                  10020
#define IDS_ERROR                       10021
#define IDS_LEXDEFAULT                  10022
#define IDS_LEXMSDOS                    10023
#define IDS_LEXHTML                     10024
#define IDS_LEXXML                      10025
#define IDS_LEXCSS                      10026
#define IDS_LEXCPP                      10027
#define IDS_LEXCS                       10028
#define IDS_LEXRC                       10029
#define IDS_LEXMAK                      10030
#define IDS_LEXVBS                      10031
#define IDS_LEXVB                       10032
#define IDS_LEXJS                       10033
#define IDS_LEXJAVA                     10034
#define IDS_LEXPAS                      10035
#define IDS_LEXASM                      10036
#define IDS_LEXPL                       10037
#define IDS_LEXINI                      10038
#define IDS_LEXBAT                      10039
#define IDS_LEXDIFF                     10040
#define IDS_LEXSQL                      10041
#define IDS_LEXAS                       10042
#define IDS_LEXNSIS                     10043
#define IDS_LEXPY                       10044
#define IDS_LEXRUBY                     10045
#define IDS_LEXREG                      10046
#define IDS_CHARCOUNT                   10047
#define IDS_ASSOC_TYPE                  10048
#define IDS_OPENBY                      10049
#define IDS_UNKNOWN_FILE                10050
#define IDS_LEXH                        10051
#define IDS_LEXSUB                      10052
#define IDS_ERR_ALREADY_EXISTS          10053
#define IDS_ERR_NOTFOUND                10054
#define IDS_EOLMODE                     10055
#define IDS_BADFILECHAR                 10056
#define IDS_MODIFIED                    10057
#define IDS_ERR_REGEX                   10058
#define IDS_ABOUT                       10059
#define IDS_SETTING                     10060
#define IDS_OK                          10061
#define IDS_CANCEL                      10062
#define IDS_COLLECT                     10063
#define IDS_NAME                        10064
#define IDS_EXPRESSION                  10065
#define IDS_ERR_VERSION                 10066
#define IDS_LEXFORTRAN                  10066
#define IDS_ERR_EMPTY_FILE              10067
#define IDS_PROFILE                     10068
#define IDS_ERR_XML_PARSE               10069
#define IDS_FILTER_ALL                  11000
#define IDS_FILTER_EXE                  11001
#define IDS_OPENWITH                    11002
#define IDS_FAVORITES                   11003
#define CMD_ESCAPE                      20000
#define CMD_CTRLENTER                   20001
#define CMD_LEXDEFAULT                  20003
#define CMD_LEXHTML                     20004
#define CMD_LEXXML                      20005
#define IDM_FILE_NEW                    40000
#define IDM_FILE_OPEN                   40001
#define IDM_FILE_REVERT                 40002
#define IDM_FILE_SAVE                   40004
#define IDM_FILE_SAVEAS                 40005
#define IDM_FILE_SAVECOPY               40006
#define IDM_FILE_READONLY               40007
#define IDM_FILE_LAUNCH                 40008
#define IDM_FILE_OPENWITH               40009
#define IDM_FILE_RUN                    40010
#define IDM_FILE_NEWWINDOW              40011
#define IDM_FILE_NEWWINDOW2             40012
#define IDM_FILE_PAGESETUP              40013
#define IDM_FILE_PRINT                  40014
#define IDM_FILE_PROPERTIES             40015
#define IDM_FILE_CREATELINK             40016
#define IDM_FILE_OPENFAV                40017
#define IDM_FILE_ADDTOFAV               40018
#define IDM_FILE_MANAGEFAV              40019
#define IDM_FILE_RECENT                 40020
#define IDM_FILE_EXIT                   40021
#define IDM_ENCODING_ANSI               40100
#define IDM_ENCODING_UNICODE_LE         40101
#define IDM_ENCODING_UNICODE_BE         40102
#define IDM_ENCODING_UTF8               40103
#define IDM_ENCODING_SETDEFAULT         40105
#define ID_Menu                         40165
#define IDM_CPP_QFORMAT                 40168
#define IDM_CPP_FORMAT                  40173
#define IDM_CP_DEFAULT                  40176
#define IDM_CODEPAGE                    40177
#define IDM_RECENT_FILE                 40178
#define IDM_RELOAD_AUTO                 40179
#define IDM_RELOAD_ANSI                 40180
#define IDM_RELOAD_UNICODE_LE           40181
#define IDM_RELOAD_UNICODE_BE           40182
#define IDM_RELOAD_UTF8                 40183
#define IDM_FORMAT_SCHEME               40185
#define IDM_CPP_COMMENT                 40186
#define IDM_CPP_UNCOMMENT               40187
#define IDM_BAT_COMMENT                 40188
#define IDM_BAT_UNCOMMENT               40189
#define IDM_NSIS_COMMENT                40190
#define IDM_NSIS_UNCOMMENT              40191
#define IDM_NSIS_COMMENT2               40192
#define IDM_NSIS_COMPILE                40194
#define IDM_CPP_BATCH_FORMAT            40196
#define IDM_EXPORT                      40197
#define IDM_EXPORT_HTML                 40198
#define IDM_COPYTO_HTML                 40199
#define IDM_LINEENDINGS_CRLF            40200
#define IDM_LINEENDINGS_CR              40201
#define IDM_LINEENDINGS_LF              40202
#define IDM_LINEENDINGS_SETDEFAULT      40203
#define IDM_CMD_HELP                    40204
#define IDM_EXPORT_UBB                  40205
#define IDM_PY_COMMENT                  40206
#define IDM_PY_UNCOMMENT                40207
#define IDM_RB_COMMENT                  40208
#define IDM_RB_UNCOMMENT                40209
#define IDM_HELP_CHARCOUNT              40211
#define IDM_HELP_CMD                    40212
#define IDM_SETTING_FILEASSOCIATION     40214
#define IDM_OPENWITH_CONFIG             40216
#define IDM_SETTING_SETTINGS            40218
#define IDM_TOOLS_SETTINGS              40220
#define IDM_EDIT_COLLECT                40224
#define IDM_SINGLE_CHAR                 40227
#define IDM_ZERO_OR_MORE                40230
#define IDM_ONE_OR_MORE                 40231
#define IDM_LINEFRONT                   40232
#define IDM_LINEEND                     40233
#define IDM_ZERO_OR_ONE                 40234
#define IDM_NM                          40235
#define IDM_NG_ZERO_OR_MORE             40236
#define IDM_NG_ONE_OR_MORE              40237
#define IDM_NG_ZERO_OR_ONE              40238
#define IDM_NG_NM                       40240
#define IDM_GROUP                       40241
#define IDM_OR                          40242
#define IDM_CHAR_SET                    40243
#define IDM_NCHAR_SET                   40244
#define IDM_NEWLINE                     40245
#define IDM_CR                          40246
#define IDM_TAB                         40247
#define IDM_WORD                        40248
#define IDM_SPACE                       40251
#define IDM_DIGIT                       40253
#define IDM_LOWWER                      40255
#define IDM_LOWER                       40256
#define IDM_UPPER                       40258
#define IDM_ESC                         40260
#define IDM_CUSTOM                      40266
#define IDM_MATCH_SUBEXP0               40267
#define IDM_MATCH_SUBEXP1               40268
#define IDM_MATCH_SUBEXP2               40269
#define IDM_MATCH_SUBEXP3               40270
#define IDM_IMPORT                      40270
#define IDM_MATCH_SUBEXP4               40271
#define ID_40271                        40271
#define IDM_MATCH_SUBEXP5               40272
#define ID_40272                        40272
#define IDM_MATCH_SUBEXP6               40273
#define IDM_MATCH_SUBEXP7               40274
#define IDM_MATCH_SUBEXP8               40275
#define IDM_MATCH_SUBEXP9               40276
#define IDM_EDIT_UNDO                   40300
#define IDM_EDIT_REDO                   40301
#define IDM_EDIT_CUT                    40302
#define IDM_EDIT_COPY                   40303
#define IDM_EDIT_COPYALL                40304
#define IDM_EDIT_PASTE                  40305
#define IDM_EDIT_CLEAR                  40306
#define IDM_EDIT_CLEARALL               40307
#define IDM_EDIT_SELECTALL              40308
#define IDM_EDIT_SELECTWORD             40309
#define IDM_EDIT_MOVELINEUP             40310
#define IDM_EDIT_MOVELINEDOWN           40311
#define IDM_EDIT_TOGGLELINE             40312
#define IDM_EDIT_DUPLICATELINE          40313
#define IDM_EDIT_CUTLINE                40314
#define IDM_EDIT_COPYLINE               40315
#define IDM_EDIT_DELETELINE             40316
#define IDM_EDIT_DELETELINELEFT         40317
#define IDM_EDIT_DELETELINERIGHT        40318
#define IDM_EDIT_SPLITLINES             40319
#define IDM_EDIT_JOINLINES              40320
#define IDM_EDIT_STRIP1STCHAR           40321
#define IDM_EDIT_TRIMLINES              40322
#define IDM_EDIT_REMOVEBLANKLINES       40323
#define IDM_EDIT_INDENT                 40324
#define IDM_EDIT_UNINDENT               40325
#define IDM_EDIT_FINDMATCHINGBRACE      40326
#define IDM_EDIT_SELTOMATCHINGBRACE     40327
#define IDM_EDIT_CONVERTUPPERCASE       40328
#define IDM_EDIT_CONVERTLOWERCASE       40329
#define IDM_EDIT_CONVERTTABS            40330
#define IDM_EDIT_CONVERTSPACES          40331
#define IDM_EDIT_CONVERTOEM             40332
#define IDM_EDIT_CONVERTANSI            40333
#define IDM_EDIT_INSERT_SHORTDATE       40334
#define IDM_EDIT_INSERT_LONGDATE        40335
#define IDM_EDIT_INSERT_FILENAME        40336
#define IDM_EDIT_INSERT_PATHNAME        40337
#define IDM_EDIT_FIND                   40338
#define IDM_EDIT_FINDNEXT               40339
#define IDM_EDIT_FINDPREV               40340
#define IDM_EDIT_REPLACE                40341
#define IDM_EDIT_GOTOLINE               40342
#define IDM_EDIT_BOOKMARK_NEXT          40343
#define IDM_EDIT_BOOKMARK_PREV          40344
#define IDM_EDIT_BOOKMARK_TOGGLE        40345
#define IDM_EDIT_BOOKMARK_CLEARALL      40346
#define IDM_VIEW_SCHEME                 40400
#define IDM_VIEW_USE2NDDEFAULT          40401
#define IDM_VIEW_SCHEMECONFIG           40402
#define IDM_VIEW_WORDWRAP               40403
#define IDM_VIEW_WORDWRAPSETTINGS       40404
#define IDM_VIEW_LONGLINEMARKER         40405
#define IDM_VIEW_LONGLINESETTINGS       40406
#define IDM_VIEW_TABSETTINGS            40408
#define IDM_VIEW_SHOWINDENTGUIDES       40409
#define IDM_VIEW_AUTOINDENTTEXT         40410
#define IDM_VIEW_LINENUMBERS            40411
#define IDM_VIEW_MARGIN                 40412
#define IDM_VIEW_SHOWWHITESPACE         40413
#define IDM_VIEW_SHOWEOLS               40414
#define IDM_VIEW_WORDWRAPSYMBOLS        40415
#define IDM_VIEW_MATCHBRACES            40416
#define IDM_VIEW_AUTOCLOSETAGS          40417
#define IDM_VIEW_ZOOMIN                 40418
#define IDM_VIEW_ZOOMOUT                40419
#define IDM_VIEW_RESETZOOM              40420
#define IDM_VIEW_TOOLBAR                40421
#define IDM_VIEW_CUSTOMIZETB            40422
#define IDM_VIEW_STATUSBAR              40423
#define IDM_VIEW_TRANSPARENT            40427
#define IDM_VIEW_NOSAVERECENT           40429
#define IDM_VIEW_SAVESETTINGS           40435
#define IDM_HELP_ABOUT                  40500
#define IDM_TRAY_RESTORE                40600
#define IDM_TRAY_EXIT                   40601
#define IDT_FILE_NEW                    40700
#define IDT_FILE_OPEN                   40701
#define IDT_VIEW_ALWAYSONTOP            40702
#define IDT_FILE_SAVE                   40703
#define IDT_EDIT_UNDO                   40704
#define IDT_EDIT_REDO                   40705
#define IDT_EDIT_CUT                    40706
#define IDT_EDIT_COPY                   40707
#define IDT_EDIT_PASTE                  40708
#define IDT_EDIT_FIND                   40709
#define IDT_EDIT_REPLACE                40710
#define IDT_VIEW_WORDWRAP               40711
#define IDT_VIEW_ZOOMIN                 40712
#define IDT_VIEW_ZOOMOUT                40713
#define IDT_VIEW_SCHEME                 40714
#define IDT_VIEW_SCHEMECONFIG           40715
#define IDT_FILE_EXIT                   40716
#define IDT_FILE_SAVEAS                 40717
#define IDT_FILE_SAVECOPY               40718
#define IDT_EDIT_CLEAR                  40719
#define IDT_EDIT_COPYALL                40720
#define IDT_EDIT_FINDNEXT               40721
#define IDT_EDIT_FINDPREV               40722
#define IDT_FILE_PRINT                  40723
#define IDT_FILE_OPENFAV                40724
#define IDT_FILE_ADDTOFAV               40725
#define IDS_ERR_LOADFILE                50000
#define IDS_ERR_SAVEFILE                50001
#define IDS_ERR_MRUDLG                  50003
#define IDS_ERR_CREATELINK              50004
#define IDS_ERR_PREVWINDISABLED         50005
#define IDS_SELRECT                     50006
#define IDS_FIND_WRAPFW                 50007
#define IDS_FIND_WRAPRE                 50008
#define IDS_NOTFOUND                    50009
#define IDS_REPLCOUNT                   50010
#define IDS_ASK_ENCODING                50011
#define IDS_ERR_UNICODE                 50012
#define IDS_WARNLOADBIGFILE             50013
#define IDS_WORDWRAPVISUALS             50014
#define IDS_SAVESETTINGS                50015
#define IDS_ERR_DROP                    50016
#define IDS_ASK_SAVE                    50017
#define IDS_ASK_CREATE                  50018
#define IDS_PRINT_HEADER                50019
#define IDS_PRINT_FOOTER                50020
#define IDS_PRINT_PAGENUM               50021
#define IDS_PRINT_EMPTY                 50022
#define IDS_PRINT_ERROR                 50023
#define IDS_FAV_SUCCESS                 50024
#define IDS_FAV_FAILURE                 50025
#define IDS_READONLY_MODIFY             50026
#define IDS_READONLY_SAVE               50027
#define IDS_ENCODING                    50028
#define IDS_CMDLINEHELP                 60000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        347
#define _APS_NEXT_COMMAND_VALUE         40273
#define _APS_NEXT_CONTROL_VALUE         1259
#define _APS_NEXT_SYMED_VALUE           137
#endif
#endif
